---
title: "2017_03_22 590 final project proposal"
author: "Abby"
date: "March 22, 2017"
output: md_document
---
# Thesis Data Analysis 
## Problem 
The plan for my project is to create an efficient way to analyze and reproduce my thesis data. The problem is that I have several scripts doing the exact same thing to different (~16) raw data files. The scripts have also become very messy over the past two years so organizing them in a way with proper notation is critical for my future self and any lab members who need to view that data after I leave. 

## Project Type
The project will be data analysis project but there will be a few functions created to aid in analysis. 

## Data collection and Purpose 
The project will use data that I have collected over the course of my masters degree. The idea behind my research is to investigate environmnetal controsl on extracellular enzymes in freshwater. I did this in three different experiments 1) storage 2)enzyme activity in TN and PA 3)effects of adding carbon.This data was collected in both eastern TN and north eastern PA. Several graphs will be produced as well as a final CSV with all of my thesis data in one place.This will help with advisor use the data at a later date.  I will also create functions that should aid in future users analyzing enzyme data, 